name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: ["1.22"]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install libpcap-dev
        run: sudo apt install -y libpcap-dev

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Go dependencies
        run: go mod download
        env:
          GOPROXY: "https://proxy.golang.org"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
